I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/capitulo3.rpy", line 301, in script
    $ hablar(maestro,"Maestro Neutral","Eh?")
  File "game/capitulo3.rpy", line 301, in <module>
    $ hablar(maestro,"Maestro Neutral","Eh?")
  File "game/personajes.rpy", line 44, in hablar
    renpy.say(personaje, texto)
NameError: name 'maestrOO' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/capitulo3.rpy", line 301, in script
    $ hablar(maestro,"Maestro Neutral","Eh?")
  File "C:\Users\samue\Downloads\renpy-8.3.7-sdk\renpy\ast.py", line 834, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\samue\Downloads\renpy-8.3.7-sdk\renpy\python.py", line 1187, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/capitulo3.rpy", line 301, in <module>
    $ hablar(maestro,"Maestro Neutral","Eh?")
  File "game/personajes.rpy", line 44, in hablar
    renpy.say(personaje, texto)
  File "C:\Users\samue\Downloads\renpy-8.3.7-sdk\renpy\exports\sayexports.py", line 132, in say
    who(what, *args, **kwargs)
  File "C:\Users\samue\Downloads\renpy-8.3.7-sdk\renpy\character.py", line 1451, in __call__
    who = renpy.python.py_eval(who)
  File "C:\Users\samue\Downloads\renpy-8.3.7-sdk\renpy\python.py", line 1218, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\samue\Downloads\renpy-8.3.7-sdk\renpy\python.py", line 1211, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "<none>", line 1, in <module>
NameError: name 'maestrOO' is not defined

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
Proj1 Beta 0.1
Sat Jun 28 00:26:52 2025
